"""add normalized content system

Revision ID: 19551f9f4fef
Revises: c8be1dfa3b5f
Create Date: 2026-08-13 22:21:28.638377

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '19551f9f4fef'
down_revision: Union[str, Sequence[str], None] = 'c8be1dfa3b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    content_status = postgresql.ENUM(
        'draft', 'published', 'archived', name='content_status', create_type=False
    )
    content_status.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_provider', 'storage_key', name='uq_audio_storage_key')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hsk_level_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('title_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('course_type', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', content_status, server_default='published', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hsk_level_id'], ['hsk_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hsk_level_id', 'course_type', name='uq_course_level_type'),
    sa.UniqueConstraint('hsk_level_id', 'sort_order', name='uq_course_level_order')
    )
    op.create_index(op.f('ix_courses_hsk_level_id'), 'courses', ['hsk_level_id'], unique=False)
    op.create_index(op.f('ix_courses_status'), 'courses', ['status'], unique=False)
    op.create_table('example_sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chinese', sa.Text(), nullable=False),
    sa.Column('pinyin', sa.Text(), nullable=True),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audio_asset_id', sa.Integer(), nullable=True),
    sa.Column('status', content_status, server_default='published', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chinese', 'pinyin', name='uq_example_chinese_pinyin')
    )
    op.create_index(op.f('ix_example_sentences_audio_asset_id'), 'example_sentences', ['audio_asset_id'], unique=False)
    op.create_index(op.f('ix_example_sentences_status'), 'example_sentences', ['status'], unique=False)
    op.create_table('grammar_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hsk_level_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('title_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pattern', sa.String(length=500), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', content_status, server_default='published', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hsk_level_id'], ['hsk_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hsk_level_id', 'title', name='uq_grammar_level_title')
    )
    op.create_index(op.f('ix_grammar_points_hsk_level_id'), 'grammar_points', ['hsk_level_id'], unique=False)
    op.create_index(op.f('ix_grammar_points_status'), 'grammar_points', ['status'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.Enum('hsk_levels', 'courses', 'lessons', 'vocabulary', 'grammar', 'example_sentences', name='import_entity_type'), nullable=False),
    sa.Column('source_format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='import_job_status'), server_default='pending', nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('created_records', sa.Integer(), nullable=False),
    sa.Column('updated_records', sa.Integer(), nullable=False),
    sa.Column('skipped_records', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_jobs_entity_status', 'import_jobs', ['entity_type', 'status'], unique=False)
    op.create_index(op.f('ix_import_jobs_requested_by_user_id'), 'import_jobs', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hsk_level_id', sa.Integer(), nullable=False),
    sa.Column('simplified', sa.String(length=80), nullable=False),
    sa.Column('traditional', sa.String(length=80), nullable=True),
    sa.Column('pinyin', sa.String(length=160), nullable=True),
    sa.Column('meaning_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('part_of_speech', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('audio_asset_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', content_status, server_default='published', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hsk_level_id'], ['hsk_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hsk_level_id', 'simplified', 'pinyin', name='uq_vocabulary_level_simplified_pinyin')
    )
    op.create_index(op.f('ix_vocabulary_audio_asset_id'), 'vocabulary', ['audio_asset_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_category'), 'vocabulary', ['category'], unique=False)
    op.create_index(op.f('ix_vocabulary_hsk_level_id'), 'vocabulary', ['hsk_level_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_part_of_speech'), 'vocabulary', ['part_of_speech'], unique=False)
    op.create_index(op.f('ix_vocabulary_pinyin'), 'vocabulary', ['pinyin'], unique=False)
    op.create_index('ix_vocabulary_search', 'vocabulary', ['simplified', 'pinyin'], unique=False)
    op.create_index(op.f('ix_vocabulary_simplified'), 'vocabulary', ['simplified'], unique=False)
    op.create_index(op.f('ix_vocabulary_status'), 'vocabulary', ['status'], unique=False)
    op.create_index(
        'uq_vocabulary_level_simplified_missing_pinyin',
        'vocabulary',
        ['hsk_level_id', 'simplified'],
        unique=True,
        postgresql_where=sa.text('pinyin IS NULL'),
    )
    op.create_table('grammar_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grammar_point_id', sa.Integer(), nullable=False),
    sa.Column('example_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['example_id'], ['example_sentences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grammar_point_id', 'example_id', name='uq_grammar_example')
    )
    op.create_index(op.f('ix_grammar_examples_example_id'), 'grammar_examples', ['example_id'], unique=False)
    op.create_index(op.f('ix_grammar_examples_grammar_point_id'), 'grammar_examples', ['grammar_point_id'], unique=False)
    op.create_table('user_grammar_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grammar_point_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('viewed', 'completed', name='grammar_learning_status'), server_default='viewed', nullable=False),
    sa.Column('first_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'grammar_point_id', name='uq_user_grammar_progress')
    )
    op.create_index(op.f('ix_user_grammar_progress_grammar_point_id'), 'user_grammar_progress', ['grammar_point_id'], unique=False)
    op.create_index(op.f('ix_user_grammar_progress_user_id'), 'user_grammar_progress', ['user_id'], unique=False)
    op.create_index('ix_user_grammar_progress_user_status', 'user_grammar_progress', ['user_id', 'status'], unique=False)
    op.create_table('user_vocabulary_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'learning', 'learned', 'mastered', name='vocabulary_learning_status'), server_default='new', nullable=False),
    sa.Column('first_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('learned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vocabulary_id', name='uq_user_vocabulary_progress')
    )
    op.create_index(op.f('ix_user_vocabulary_progress_user_id'), 'user_vocabulary_progress', ['user_id'], unique=False)
    op.create_index('ix_user_vocabulary_progress_user_status', 'user_vocabulary_progress', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_vocabulary_progress_vocabulary_id'), 'user_vocabulary_progress', ['vocabulary_id'], unique=False)
    op.create_table('vocabulary_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('example_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['example_id'], ['example_sentences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vocabulary_id', 'example_id', name='uq_vocabulary_example')
    )
    op.create_index(op.f('ix_vocabulary_examples_example_id'), 'vocabulary_examples', ['example_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_examples_vocabulary_id'), 'vocabulary_examples', ['vocabulary_id'], unique=False)
    op.create_table('lesson_grammar_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('grammar_point_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'grammar_point_id', name='uq_lesson_grammar'),
    sa.UniqueConstraint('lesson_id', 'sort_order', name='uq_lesson_grammar_order')
    )
    op.create_index(op.f('ix_lesson_grammar_points_grammar_point_id'), 'lesson_grammar_points', ['grammar_point_id'], unique=False)
    op.create_index(op.f('ix_lesson_grammar_points_lesson_id'), 'lesson_grammar_points', ['lesson_id'], unique=False)
    op.create_table('lesson_vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'sort_order', name='uq_lesson_vocabulary_order'),
    sa.UniqueConstraint('lesson_id', 'vocabulary_id', name='uq_lesson_vocabulary')
    )
    op.create_index(op.f('ix_lesson_vocabulary_lesson_id'), 'lesson_vocabulary', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_vocabulary_vocabulary_id'), 'lesson_vocabulary', ['vocabulary_id'], unique=False)
    op.add_column('hsk_levels', sa.Column('display_order', sa.Integer(), nullable=True))
    op.execute("UPDATE hsk_levels SET display_order = level_number")
    op.alter_column('hsk_levels', 'display_order', nullable=False)
    op.add_column('hsk_levels', sa.Column('status', content_status, server_default='published', nullable=False))
    op.add_column('hsk_levels', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('hsk_levels', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('hsk_levels', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_hsk_levels_display_order'), 'hsk_levels', ['display_order'], unique=False)
    op.create_index(op.f('ix_hsk_levels_status'), 'hsk_levels', ['status'], unique=False)
    op.create_unique_constraint(
        'uq_hsk_levels_display_order', 'hsk_levels', ['display_order']
    )
    op.add_column('lesson_progress', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lesson_progress', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lesson_progress', sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lessons', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column(
        'lessons',
        sa.Column('listening_audio_asset_id', sa.Integer(), nullable=True),
    )
    op.add_column('lessons', sa.Column('content_status', content_status, server_default='published', nullable=False))
    op.add_column('lessons', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('lessons', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('lessons', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_lessons_content_status'), 'lessons', ['content_status'], unique=False)
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_index(
        op.f('ix_lessons_listening_audio_asset_id'),
        'lessons',
        ['listening_audio_asset_id'],
        unique=False,
    )
    op.execute(
        """
        WITH course_groups AS (
            SELECT DISTINCT
                l.hsk_level_id,
                h.level_number,
                l.lesson_type,
                CASE l.lesson_type
                    WHEN 'mixed' THEN 1
                    WHEN 'vocabulary' THEN 2
                    WHEN 'grammar' THEN 3
                    WHEN 'reading' THEN 4
                    WHEN 'listening' THEN 5
                    WHEN 'writing' THEN 6
                    WHEN 'sentence_pattern' THEN 7
                    WHEN 'conversation' THEN 8
                    WHEN 'practice' THEN 9
                    WHEN 'review' THEN 10
                    WHEN 'quiz' THEN 11
                    ELSE 99
                END AS course_order
            FROM lessons l
            JOIN hsk_levels h ON h.id = l.hsk_level_id
        )
        INSERT INTO courses (
            hsk_level_id,
            title,
            title_translations,
            description,
            course_type,
            sort_order,
            status,
            metadata
        )
        SELECT
            hsk_level_id,
            'HSK ' || level_number || ' ' ||
                initcap(replace(lesson_type, '_', ' ')),
            jsonb_build_object(
                'en', 'HSK ' || level_number || ' ' ||
                    initcap(replace(lesson_type, '_', ' ')),
                'vi', 'HSK ' || level_number || ' - ' ||
                    initcap(replace(lesson_type, '_', ' '))
            ),
            'Existing ' || replace(lesson_type, '_', ' ') || ' lessons.',
            lesson_type,
            course_order,
            'published',
            jsonb_build_object('source', 'phase4_legacy_backfill')
        FROM course_groups
        ON CONFLICT (hsk_level_id, course_type) DO NOTHING
        """
    )
    op.execute(
        """
        UPDATE lessons l
        SET course_id = c.id
        FROM courses c
        WHERE c.hsk_level_id = l.hsk_level_id
          AND c.course_type = l.lesson_type
        """
    )
    op.alter_column('lessons', 'course_id', nullable=False)
    op.create_unique_constraint('uq_lesson_course_title', 'lessons', ['course_id', 'title'])
    op.create_unique_constraint(
        'uq_lesson_course_order', 'lessons', ['course_id', 'sort_order']
    )
    op.create_foreign_key(
        'fk_lessons_course_id_courses',
        'lessons',
        'courses',
        ['course_id'],
        ['id'],
        ondelete='RESTRICT',
    )
    op.create_foreign_key(
        'fk_lessons_listening_audio_asset_id_audio_assets',
        'lessons',
        'audio_assets',
        ['listening_audio_asset_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.add_column('saved_words', sa.Column('vocabulary_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_saved_words_vocabulary_id'), 'saved_words', ['vocabulary_id'], unique=False)
    op.create_unique_constraint('uq_saved_words_user_vocabulary', 'saved_words', ['user_id', 'vocabulary_id'])
    op.drop_constraint('uq_saved_words_user_hanzi', 'saved_words', type_='unique')
    op.create_foreign_key(
        'fk_saved_words_vocabulary_id_vocabulary',
        'saved_words',
        'vocabulary',
        ['vocabulary_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_check_constraint(
        'ck_hsk_levels_level_number', 'hsk_levels', 'level_number BETWEEN 1 AND 6'
    )
    op.create_check_constraint(
        'ck_hsk_levels_display_order', 'hsk_levels', 'display_order >= 0'
    )
    op.create_check_constraint('ck_courses_sort_order', 'courses', 'sort_order >= 0')
    op.create_check_constraint(
        'ck_courses_title_not_empty', 'courses', "length(trim(title)) > 0"
    )
    op.create_check_constraint(
        'ck_lessons_duration', 'lessons', 'duration_minutes > 0'
    )
    op.create_check_constraint(
        'ck_lessons_difficulty', 'lessons', 'difficulty IS NULL OR difficulty BETWEEN 1 AND 6'
    )
    op.create_check_constraint(
        'ck_vocabulary_simplified_not_empty',
        'vocabulary',
        "length(trim(simplified)) > 0",
    )
    op.create_check_constraint(
        'ck_vocabulary_difficulty',
        'vocabulary',
        'difficulty IS NULL OR difficulty BETWEEN 1 AND 6',
    )
    op.create_check_constraint(
        'ck_vocabulary_display_order', 'vocabulary', 'display_order >= 0'
    )
    op.create_check_constraint(
        'ck_grammar_title_not_empty', 'grammar_points', "length(trim(title)) > 0"
    )
    op.create_check_constraint(
        'ck_grammar_difficulty',
        'grammar_points',
        'difficulty IS NULL OR difficulty BETWEEN 1 AND 6',
    )
    op.create_check_constraint(
        'ck_example_chinese_not_empty',
        'example_sentences',
        "length(trim(chinese)) > 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_lessons_difficulty', 'lessons', type_='check')
    op.drop_constraint('ck_lessons_duration', 'lessons', type_='check')
    op.drop_constraint('uq_lesson_course_order', 'lessons', type_='unique')
    op.drop_constraint('ck_hsk_levels_display_order', 'hsk_levels', type_='check')
    op.drop_constraint('ck_hsk_levels_level_number', 'hsk_levels', type_='check')
    op.drop_constraint(
        'uq_hsk_levels_display_order', 'hsk_levels', type_='unique'
    )
    op.drop_constraint(
        'fk_saved_words_vocabulary_id_vocabulary',
        'saved_words',
        type_='foreignkey',
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'uq_saved_words_user_hanzi'
            ) THEN
                ALTER TABLE saved_words
                ADD CONSTRAINT uq_saved_words_user_hanzi UNIQUE (user_id, hanzi);
            END IF;
        END
        $$;
        """
    )
    op.drop_constraint('uq_saved_words_user_vocabulary', 'saved_words', type_='unique')
    op.drop_index(op.f('ix_saved_words_vocabulary_id'), table_name='saved_words')
    op.drop_column('saved_words', 'vocabulary_id')
    op.drop_constraint('fk_lessons_course_id_courses', 'lessons', type_='foreignkey')
    op.drop_constraint(
        'fk_lessons_listening_audio_asset_id_audio_assets',
        'lessons',
        type_='foreignkey',
    )
    op.drop_constraint('uq_lesson_course_title', 'lessons', type_='unique')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_index(
        op.f('ix_lessons_listening_audio_asset_id'), table_name='lessons'
    )
    op.drop_index(op.f('ix_lessons_content_status'), table_name='lessons')
    op.drop_column('lessons', 'updated_at')
    op.drop_column('lessons', 'created_at')
    op.drop_column('lessons', 'metadata')
    op.drop_column('lessons', 'content_status')
    op.drop_column('lessons', 'difficulty')
    op.drop_column('lessons', 'listening_audio_asset_id')
    op.drop_column('lessons', 'course_id')
    op.drop_column('lesson_progress', 'last_viewed_at')
    op.drop_column('lesson_progress', 'completed_at')
    op.drop_column('lesson_progress', 'started_at')
    op.drop_index(op.f('ix_hsk_levels_status'), table_name='hsk_levels')
    op.drop_index(op.f('ix_hsk_levels_display_order'), table_name='hsk_levels')
    op.drop_column('hsk_levels', 'updated_at')
    op.drop_column('hsk_levels', 'created_at')
    op.drop_column('hsk_levels', 'metadata')
    op.drop_column('hsk_levels', 'status')
    op.drop_column('hsk_levels', 'display_order')
    op.drop_index(op.f('ix_lesson_vocabulary_vocabulary_id'), table_name='lesson_vocabulary')
    op.drop_index(op.f('ix_lesson_vocabulary_lesson_id'), table_name='lesson_vocabulary')
    op.drop_table('lesson_vocabulary')
    op.drop_index(op.f('ix_lesson_grammar_points_lesson_id'), table_name='lesson_grammar_points')
    op.drop_index(op.f('ix_lesson_grammar_points_grammar_point_id'), table_name='lesson_grammar_points')
    op.drop_table('lesson_grammar_points')
    op.drop_index(op.f('ix_vocabulary_examples_vocabulary_id'), table_name='vocabulary_examples')
    op.drop_index(op.f('ix_vocabulary_examples_example_id'), table_name='vocabulary_examples')
    op.drop_table('vocabulary_examples')
    op.drop_index(op.f('ix_user_vocabulary_progress_vocabulary_id'), table_name='user_vocabulary_progress')
    op.drop_index('ix_user_vocabulary_progress_user_status', table_name='user_vocabulary_progress')
    op.drop_index(op.f('ix_user_vocabulary_progress_user_id'), table_name='user_vocabulary_progress')
    op.drop_table('user_vocabulary_progress')
    op.drop_index('ix_user_grammar_progress_user_status', table_name='user_grammar_progress')
    op.drop_index(op.f('ix_user_grammar_progress_user_id'), table_name='user_grammar_progress')
    op.drop_index(op.f('ix_user_grammar_progress_grammar_point_id'), table_name='user_grammar_progress')
    op.drop_table('user_grammar_progress')
    op.drop_index(op.f('ix_grammar_examples_grammar_point_id'), table_name='grammar_examples')
    op.drop_index(op.f('ix_grammar_examples_example_id'), table_name='grammar_examples')
    op.drop_table('grammar_examples')
    op.drop_index(op.f('ix_vocabulary_status'), table_name='vocabulary')
    op.execute('DROP INDEX IF EXISTS uq_vocabulary_level_simplified_missing_pinyin')
    op.drop_index(op.f('ix_vocabulary_simplified'), table_name='vocabulary')
    op.drop_index('ix_vocabulary_search', table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_pinyin'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_part_of_speech'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_hsk_level_id'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_category'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_audio_asset_id'), table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_requested_by_user_id'), table_name='import_jobs')
    op.drop_index('ix_import_jobs_entity_status', table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_grammar_points_status'), table_name='grammar_points')
    op.drop_index(op.f('ix_grammar_points_hsk_level_id'), table_name='grammar_points')
    op.drop_table('grammar_points')
    op.drop_index(op.f('ix_example_sentences_status'), table_name='example_sentences')
    op.drop_index(op.f('ix_example_sentences_audio_asset_id'), table_name='example_sentences')
    op.drop_table('example_sentences')
    op.drop_index(op.f('ix_courses_status'), table_name='courses')
    op.drop_index(op.f('ix_courses_hsk_level_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_table('audio_assets')
    postgresql.ENUM(name='grammar_learning_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='vocabulary_learning_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='import_job_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='import_entity_type').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='content_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
