"""phase6_11 listening speaking progress srs exam writing

Revision ID: 425a10299bbd
Revises: bf3838832640
Create Date: 2026-09-02 15:44:37.291971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '425a10299bbd'
down_revision: Union[str, Sequence[str], None] = 'bf3838832640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('exam_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('current_section', sa.String(length=40), nullable=True),
    sa.Column('question_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('section_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['mock_tests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_attempts_exam_id'), 'exam_attempts', ['exam_id'], unique=False)
    op.create_index('ix_exam_attempts_exam_user', 'exam_attempts', ['exam_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_exam_attempts_status'), 'exam_attempts', ['status'], unique=False)
    op.create_index('ix_exam_attempts_user_created', 'exam_attempts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_exam_attempts_user_id'), 'exam_attempts', ['user_id'], unique=False)
    op.create_index('ix_exam_attempts_user_status', 'exam_attempts', ['user_id', 'status'], unique=False)
    op.create_table('review_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.String(length=40), nullable=False),
    sa.Column('content_key', sa.String(length=180), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=True),
    sa.Column('grammar_id', sa.String(length=180), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('scheduler_version', sa.String(length=40), nullable=False),
    sa.Column('content_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(card_type = 'VOCABULARY' AND grammar_id IS NULL) OR (card_type = 'GRAMMAR' AND grammar_id IS NOT NULL AND vocabulary_id IS NULL)", name='ck_review_cards_one_content_ref'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_type', 'content_key', name='uq_review_cards_user_content')
    )
    op.create_index('ix_review_cards_grammar', 'review_cards', ['grammar_id'], unique=False)
    op.create_index(op.f('ix_review_cards_state'), 'review_cards', ['state'], unique=False)
    op.create_index('ix_review_cards_user_due', 'review_cards', ['user_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_review_cards_user_id'), 'review_cards', ['user_id'], unique=False)
    op.create_index('ix_review_cards_user_type', 'review_cards', ['user_id', 'card_type'], unique=False)
    op.create_index('ix_review_cards_vocabulary', 'review_cards', ['vocabulary_id'], unique=False)
    op.create_table('speech_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('upload_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_provider', 'storage_key', name='uq_speech_recordings_storage_key')
    )
    op.create_index('ix_speech_recordings_expires_at', 'speech_recordings', ['expires_at'], unique=False)
    op.create_index(op.f('ix_speech_recordings_language'), 'speech_recordings', ['language'], unique=False)
    op.create_index(op.f('ix_speech_recordings_status'), 'speech_recordings', ['status'], unique=False)
    op.create_index(op.f('ix_speech_recordings_user_id'), 'speech_recordings', ['user_id'], unique=False)
    op.create_index('ix_speech_recordings_user_status', 'speech_recordings', ['user_id', 'status'], unique=False)
    op.create_table('review_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('previous_state', sa.String(length=40), nullable=False),
    sa.Column('new_state', sa.String(length=40), nullable=False),
    sa.Column('previous_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_stability', sa.Float(), nullable=True),
    sa.Column('new_stability', sa.Float(), nullable=True),
    sa.Column('previous_difficulty', sa.Float(), nullable=True),
    sa.Column('new_difficulty', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['review_cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_review_history_user_key')
    )
    op.create_index(op.f('ix_review_history_card_id'), 'review_history', ['card_id'], unique=False)
    op.create_index('ix_review_history_card_reviewed', 'review_history', ['card_id', 'reviewed_at'], unique=False)
    op.create_index(op.f('ix_review_history_source'), 'review_history', ['source'], unique=False)
    op.create_index(op.f('ix_review_history_user_id'), 'review_history', ['user_id'], unique=False)
    op.create_index('ix_review_history_user_reviewed', 'review_history', ['user_id', 'reviewed_at'], unique=False)
    op.create_table('exam_question_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_attempt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['exam_attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_attempt_id', 'question_id', name='uq_exam_question_results_attempt_question')
    )
    op.create_index('ix_exam_question_results_attempt', 'exam_question_results', ['exam_attempt_id'], unique=False)
    op.create_index(op.f('ix_exam_question_results_exam_attempt_id'), 'exam_question_results', ['exam_attempt_id'], unique=False)
    op.create_index('ix_exam_question_results_question', 'exam_question_results', ['question_id'], unique=False)
    op.create_index(op.f('ix_exam_question_results_question_id'), 'exam_question_results', ['question_id'], unique=False)
    op.create_index(op.f('ix_exam_question_results_section'), 'exam_question_results', ['section'], unique=False)
    op.create_index(op.f('ix_exam_question_results_user_id'), 'exam_question_results', ['user_id'], unique=False)
    op.create_table('speaking_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('practice_session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_attempt_id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_model_version', sa.String(length=120), nullable=True),
    sa.Column('recognized_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('pronunciation_score', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('word_feedback', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tone_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback_label', sa.String(length=80), nullable=True),
    sa.Column('processing_status', sa.String(length=40), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['answer_attempt_id'], ['question_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recording_id'], ['speech_recordings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_attempt_id', name='uq_speaking_attempts_answer_attempt')
    )
    op.create_index(op.f('ix_speaking_attempts_answer_attempt_id'), 'speaking_attempts', ['answer_attempt_id'], unique=False)
    op.create_index(op.f('ix_speaking_attempts_practice_session_id'), 'speaking_attempts', ['practice_session_id'], unique=False)
    op.create_index(op.f('ix_speaking_attempts_processing_status'), 'speaking_attempts', ['processing_status'], unique=False)
    op.create_index(op.f('ix_speaking_attempts_question_id'), 'speaking_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_speaking_attempts_recording_id'), 'speaking_attempts', ['recording_id'], unique=False)
    op.create_index('ix_speaking_attempts_session_question', 'speaking_attempts', ['practice_session_id', 'question_id'], unique=False)
    op.create_index(op.f('ix_speaking_attempts_user_id'), 'speaking_attempts', ['user_id'], unique=False)
    op.create_index('ix_speaking_attempts_user_status', 'speaking_attempts', ['user_id', 'processing_status'], unique=False)
    op.add_column('audio_assets', sa.Column('provider', sa.String(length=40), server_default='tts', nullable=False))
    op.add_column('audio_assets', sa.Column('mime_type', sa.String(length=120), server_default='audio/mpeg', nullable=False))
    op.add_column('audio_assets', sa.Column('duration_seconds', sa.Float(), nullable=True))
    op.add_column('audio_assets', sa.Column('language', sa.String(length=20), server_default='zh-CN', nullable=False))
    op.add_column('audio_assets', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('audio_assets', sa.Column('pinyin', sa.Text(), nullable=True))
    op.add_column('audio_assets', sa.Column('translation', sa.Text(), nullable=True))
    op.add_column('audio_assets', sa.Column('status', sa.String(length=40), server_default='READY', nullable=False))
    op.create_index(op.f('ix_audio_assets_language'), 'audio_assets', ['language'], unique=False)
    op.create_index(op.f('ix_audio_assets_status'), 'audio_assets', ['status'], unique=False)
    op.create_index('ix_audio_assets_status_language', 'audio_assets', ['status', 'language'], unique=False)
    op.add_column('lesson_progress', sa.Column('speaking_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('lesson_progress', sa.Column('speaking_acceptable_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('lesson_progress', sa.Column('pronunciation_score_avg', sa.Float(), nullable=True))
    op.add_column('lesson_progress', sa.Column('last_speaking_practice', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mock_tests', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('mock_tests', sa.Column('exam_type', sa.String(length=40), server_default='MOCK', nullable=False))
    op.add_column('mock_tests', sa.Column('status', sa.String(length=40), server_default='PUBLISHED', nullable=False))
    op.add_column('mock_tests', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('mock_tests', sa.Column('blueprint', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('mock_tests', sa.Column('scoring_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('mock_tests', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('mock_tests', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mock_tests', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_mock_tests_status'), 'mock_tests', ['status'], unique=False)
    op.add_column('profiles', sa.Column('longest_streak_days', sa.Integer(), server_default='0', nullable=False))
    op.add_column('profiles', sa.Column('last_active_date', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('timezone', sa.String(length=80), server_default='Asia/Ho_Chi_Minh', nullable=False))
    op.add_column('profiles', sa.Column('daily_new_cards_limit', sa.Integer(), server_default='10', nullable=False))
    op.add_column('profiles', sa.Column('daily_review_cards_limit', sa.Integer(), server_default='50', nullable=False))
    op.add_column('question_attempts', sa.Column('attempt_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('questions', sa.Column('reference_type', sa.String(length=40), nullable=True))
    op.add_column('questions', sa.Column('reference_id', sa.String(length=120), nullable=True))
    op.add_column('questions', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_questions_reference_type'), 'questions', ['reference_type'], unique=False)
    op.create_index(op.f('ix_questions_reference_id'), 'questions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_questions_is_archived'), 'questions', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_is_archived'), table_name='questions')
    op.drop_index(op.f('ix_questions_reference_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_reference_type'), table_name='questions')
    op.drop_column('questions', 'is_archived')
    op.drop_column('questions', 'reference_id')
    op.drop_column('questions', 'reference_type')
    op.drop_column('question_attempts', 'attempt_metadata')
    op.drop_column('profiles', 'daily_review_cards_limit')
    op.drop_column('profiles', 'daily_new_cards_limit')
    op.drop_column('profiles', 'timezone')
    op.drop_column('profiles', 'last_active_date')
    op.drop_column('profiles', 'longest_streak_days')
    op.drop_index(op.f('ix_mock_tests_status'), table_name='mock_tests')
    op.drop_column('mock_tests', 'archived_at')
    op.drop_column('mock_tests', 'published_at')
    op.drop_column('mock_tests', 'instructions')
    op.drop_column('mock_tests', 'scoring_config')
    op.drop_column('mock_tests', 'blueprint')
    op.drop_column('mock_tests', 'version')
    op.drop_column('mock_tests', 'status')
    op.drop_column('mock_tests', 'exam_type')
    op.drop_column('mock_tests', 'description')
    op.drop_column('lesson_progress', 'last_speaking_practice')
    op.drop_column('lesson_progress', 'pronunciation_score_avg')
    op.drop_column('lesson_progress', 'speaking_acceptable_attempts')
    op.drop_column('lesson_progress', 'speaking_attempts')
    op.drop_index('ix_audio_assets_status_language', table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_status'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_language'), table_name='audio_assets')
    op.drop_column('audio_assets', 'status')
    op.drop_column('audio_assets', 'translation')
    op.drop_column('audio_assets', 'pinyin')
    op.drop_column('audio_assets', 'transcript')
    op.drop_column('audio_assets', 'language')
    op.drop_column('audio_assets', 'duration_seconds')
    op.drop_column('audio_assets', 'mime_type')
    op.drop_column('audio_assets', 'provider')
    op.drop_index('ix_speaking_attempts_user_status', table_name='speaking_attempts')
    op.drop_index(op.f('ix_speaking_attempts_user_id'), table_name='speaking_attempts')
    op.drop_index('ix_speaking_attempts_session_question', table_name='speaking_attempts')
    op.drop_index(op.f('ix_speaking_attempts_recording_id'), table_name='speaking_attempts')
    op.drop_index(op.f('ix_speaking_attempts_question_id'), table_name='speaking_attempts')
    op.drop_index(op.f('ix_speaking_attempts_processing_status'), table_name='speaking_attempts')
    op.drop_index(op.f('ix_speaking_attempts_practice_session_id'), table_name='speaking_attempts')
    op.drop_index(op.f('ix_speaking_attempts_answer_attempt_id'), table_name='speaking_attempts')
    op.drop_table('speaking_attempts')
    op.drop_index(op.f('ix_exam_question_results_user_id'), table_name='exam_question_results')
    op.drop_index(op.f('ix_exam_question_results_section'), table_name='exam_question_results')
    op.drop_index(op.f('ix_exam_question_results_question_id'), table_name='exam_question_results')
    op.drop_index('ix_exam_question_results_question', table_name='exam_question_results')
    op.drop_index(op.f('ix_exam_question_results_exam_attempt_id'), table_name='exam_question_results')
    op.drop_index('ix_exam_question_results_attempt', table_name='exam_question_results')
    op.drop_table('exam_question_results')
    op.drop_index('ix_review_history_user_reviewed', table_name='review_history')
    op.drop_index(op.f('ix_review_history_user_id'), table_name='review_history')
    op.drop_index(op.f('ix_review_history_source'), table_name='review_history')
    op.drop_index('ix_review_history_card_reviewed', table_name='review_history')
    op.drop_index(op.f('ix_review_history_card_id'), table_name='review_history')
    op.drop_table('review_history')
    op.drop_index('ix_speech_recordings_user_status', table_name='speech_recordings')
    op.drop_index(op.f('ix_speech_recordings_user_id'), table_name='speech_recordings')
    op.drop_index(op.f('ix_speech_recordings_status'), table_name='speech_recordings')
    op.drop_index(op.f('ix_speech_recordings_language'), table_name='speech_recordings')
    op.drop_index('ix_speech_recordings_expires_at', table_name='speech_recordings')
    op.drop_table('speech_recordings')
    op.drop_index('ix_review_cards_vocabulary', table_name='review_cards')
    op.drop_index('ix_review_cards_user_type', table_name='review_cards')
    op.drop_index(op.f('ix_review_cards_user_id'), table_name='review_cards')
    op.drop_index('ix_review_cards_user_due', table_name='review_cards')
    op.drop_index(op.f('ix_review_cards_state'), table_name='review_cards')
    op.drop_index('ix_review_cards_grammar', table_name='review_cards')
    op.drop_table('review_cards')
    op.drop_index('ix_exam_attempts_user_status', table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_user_id'), table_name='exam_attempts')
    op.drop_index('ix_exam_attempts_user_created', table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_status'), table_name='exam_attempts')
    op.drop_index('ix_exam_attempts_exam_user', table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_exam_id'), table_name='exam_attempts')
    op.drop_table('exam_attempts')
    # ### end Alembic commands ###
