"""add exercise engine and practice sessions

Revision ID: bf3838832640
Revises: 19551f9f4fef
Create Date: 2026-08-13 23:07:43.191902

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf3838832640'
down_revision: Union[str, Sequence[str], None] = '19551f9f4fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "ALTER TYPE import_entity_type ADD VALUE IF NOT EXISTS 'exercises'"
    )
    bind = op.get_bind()
    content_status = postgresql.ENUM(
        'draft',
        'published',
        'archived',
        name='content_status',
        create_type=False,
    )
    exercise_type = postgresql.ENUM(
        'multiple_choice',
        'multiple_select',
        'fill_blank',
        'matching',
        'ordering',
        'translation',
        'grammar',
        'reading',
        'dictation',
        'text_input',
        'vocabulary_recall',
        'listening',
        'speaking',
        'writing',
        'pronunciation',
        name='exercise_type',
        create_type=False,
    )
    practice_session_status = postgresql.ENUM(
        'in_progress',
        'completed',
        'abandoned',
        name='practice_session_status',
        create_type=False,
    )
    exercise_type.create(bind, checkfirst=True)
    practice_session_status.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill', sa.String(length=40), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', content_status, server_default='published', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty IS NULL OR difficulty BETWEEN 1 AND 6', name='ck_exercise_sets_difficulty'),
    sa.CheckConstraint('length(trim(title)) > 0', name='ck_exercise_sets_title_not_empty'),
    sa.CheckConstraint('sort_order >= 0', name='ck_exercise_sets_sort_order'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'slug', name='uq_exercise_set_lesson_slug'),
    sa.UniqueConstraint('lesson_id', 'sort_order', name='uq_exercise_set_lesson_order')
    )
    op.create_index(op.f('ix_exercise_sets_difficulty'), 'exercise_sets', ['difficulty'], unique=False)
    op.create_index(op.f('ix_exercise_sets_lesson_id'), 'exercise_sets', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_exercise_sets_skill'), 'exercise_sets', ['skill'], unique=False)
    op.create_index(op.f('ix_exercise_sets_status'), 'exercise_sets', ['status'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_set_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=180), nullable=False),
    sa.Column('exercise_type', exercise_type, nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('skill', sa.String(length=40), nullable=True),
    sa.Column('vocabulary_id', sa.Integer(), nullable=True),
    sa.Column('grammar_point_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', content_status, server_default='published', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty IS NULL OR difficulty BETWEEN 1 AND 6', name='ck_exercises_difficulty'),
    sa.CheckConstraint('length(trim(title)) > 0', name='ck_exercises_title_not_empty'),
    sa.CheckConstraint('sort_order >= 0', name='ck_exercises_sort_order'),
    sa.ForeignKeyConstraint(['exercise_set_id'], ['exercise_sets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_set_id', 'external_id', name='uq_exercise_set_external_id'),
    sa.UniqueConstraint('exercise_set_id', 'sort_order', name='uq_exercise_set_exercise_order')
    )
    op.create_index(op.f('ix_exercises_difficulty'), 'exercises', ['difficulty'], unique=False)
    op.create_index(op.f('ix_exercises_exercise_set_id'), 'exercises', ['exercise_set_id'], unique=False)
    op.create_index(op.f('ix_exercises_exercise_type'), 'exercises', ['exercise_type'], unique=False)
    op.create_index(op.f('ix_exercises_grammar_point_id'), 'exercises', ['grammar_point_id'], unique=False)
    op.create_index(op.f('ix_exercises_skill'), 'exercises', ['skill'], unique=False)
    op.create_index(op.f('ix_exercises_status'), 'exercises', ['status'], unique=False)
    op.create_index(op.f('ix_exercises_vocabulary_id'), 'exercises', ['vocabulary_id'], unique=False)
    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('exercise_set_id', sa.Integer(), nullable=False),
    sa.Column('status', practice_session_status, server_default='in_progress', nullable=False),
    sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selection_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('answered_questions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('correct_answers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('answered_questions >= 0', name='ck_practice_sessions_answered'),
    sa.CheckConstraint('answered_questions <= total_questions', name='ck_practice_sessions_answered_total'),
    sa.CheckConstraint('correct_answers >= 0', name='ck_practice_sessions_correct'),
    sa.CheckConstraint('correct_answers <= answered_questions', name='ck_practice_sessions_correct_answered'),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name='ck_practice_sessions_score'),
    sa.CheckConstraint('time_spent_seconds >= 0', name='ck_practice_sessions_time'),
    sa.CheckConstraint('total_questions >= 0', name='ck_practice_sessions_total'),
    sa.ForeignKeyConstraint(['exercise_set_id'], ['exercise_sets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sessions_exercise_set_id'), 'practice_sessions', ['exercise_set_id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_last_activity_at'), 'practice_sessions', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_practice_sessions_lesson_id'), 'practice_sessions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_status'), 'practice_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_practice_sessions_user_id'), 'practice_sessions', ['user_id'], unique=False)
    op.create_index('ix_practice_sessions_user_lesson', 'practice_sessions', ['user_id', 'lesson_id'], unique=False)
    op.create_index('ix_practice_sessions_user_status', 'practice_sessions', ['user_id', 'status'], unique=False)
    op.create_table('question_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('practice_session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('submitted_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('result_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_score > 0', name='ck_question_attempts_max_score'),
    sa.CheckConstraint('score >= 0', name='ck_question_attempts_score'),
    sa.CheckConstraint('score <= max_score', name='ck_question_attempts_score_max'),
    sa.CheckConstraint('time_spent_seconds >= 0', name='ck_question_attempts_time'),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_session_id', 'idempotency_key', name='uq_question_attempt_session_idempotency')
    )
    op.create_index(op.f('ix_question_attempts_attempted_at'), 'question_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_question_attempts_is_correct'), 'question_attempts', ['is_correct'], unique=False)
    op.create_index(op.f('ix_question_attempts_practice_session_id'), 'question_attempts', ['practice_session_id'], unique=False)
    op.create_index(op.f('ix_question_attempts_question_id'), 'question_attempts', ['question_id'], unique=False)
    op.create_index('ix_question_attempts_session_question', 'question_attempts', ['practice_session_id', 'question_id'], unique=False)
    op.create_index('ix_question_attempts_user_attempted', 'question_attempts', ['user_id', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_question_attempts_user_id'), 'question_attempts', ['user_id'], unique=False)
    op.add_column('questions', sa.Column('exercise_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('external_id', sa.String(length=180), nullable=True))
    op.add_column('questions', sa.Column('instruction', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('points', sa.Integer(), server_default='1', nullable=False))
    op.add_column('questions', sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('questions', sa.Column('status', content_status, server_default='published', nullable=False))
    op.add_column('questions', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_exercise_id'), 'questions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_unique_constraint('uq_question_exercise_external_id', 'questions', ['exercise_id', 'external_id'])
    op.create_unique_constraint('uq_question_exercise_order', 'questions', ['exercise_id', 'sort_order'])
    op.create_foreign_key('fk_questions_exercise_id_exercises', 'questions', 'exercises', ['exercise_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint('ck_questions_difficulty', 'questions', 'difficulty IS NULL OR difficulty BETWEEN 1 AND 6')
    op.create_check_constraint('ck_questions_points', 'questions', 'points > 0')
    op.create_check_constraint('ck_questions_prompt_not_empty', 'questions', 'length(trim(prompt)) > 0')
    op.create_check_constraint('ck_questions_sort_order', 'questions', 'sort_order >= 0')
    op.execute(
        """
        INSERT INTO exercise_sets (
            lesson_id, slug, title, description, skill, difficulty,
            sort_order, status, metadata
        )
        SELECT
            l.id,
            'lesson-practice',
            l.title || ' Practice',
            'Normalized practice migrated from the legacy question bank.',
            l.lesson_type,
            l.difficulty,
            0,
            'published',
            '{"source":"phase5_migration"}'::jsonb
        FROM lessons l
        WHERE EXISTS (
            SELECT 1 FROM questions q WHERE q.lesson_id = l.id
        )
        ON CONFLICT (lesson_id, slug) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO exercises (
            exercise_set_id, external_id, exercise_type, title,
            skill, difficulty, sort_order, status, metadata
        )
        SELECT
            es.id,
            'legacy-question-' || q.id,
            (
                CASE
                    WHEN q.question_type IN (
                        'multiple_choice', 'choose_meaning', 'image_matching'
                    ) THEN 'multiple_choice'
                    WHEN q.question_type = 'multiple_select' THEN 'multiple_select'
                    WHEN q.question_type = 'fill_blank' THEN 'fill_blank'
                    WHEN q.question_type = 'translation' THEN 'translation'
                    WHEN q.question_type = 'grammar' THEN 'grammar'
                    WHEN q.question_type = 'reading' THEN 'reading'
                    WHEN q.question_type IN ('listening', 'dictation') THEN 'dictation'
                    ELSE 'text_input'
                END
            )::exercise_type,
            'Question ' || q.sort_order,
            l.lesson_type,
            l.difficulty,
            q.sort_order,
            'published',
            '{"source":"phase5_migration"}'::jsonb
        FROM questions q
        JOIN lessons l ON l.id = q.lesson_id
        JOIN exercise_sets es
          ON es.lesson_id = l.id AND es.slug = 'lesson-practice'
        ON CONFLICT (exercise_set_id, external_id) DO NOTHING
        """
    )
    op.execute(
        """
        UPDATE questions q
        SET
            exercise_id = e.id,
            external_id = COALESCE(
                q.external_id,
                'legacy-question-' || q.id
            ),
            question_type = CASE
                WHEN q.question_type IN (
                    'multiple_choice', 'choose_meaning', 'image_matching'
                ) THEN 'multiple_choice'
                WHEN q.question_type = 'multiple_select' THEN 'multiple_select'
                WHEN q.question_type = 'fill_blank' THEN 'fill_blank'
                WHEN q.question_type = 'translation' THEN 'translation'
                WHEN q.question_type = 'grammar' THEN 'grammar'
                WHEN q.question_type = 'reading' THEN 'reading'
                WHEN q.question_type IN ('listening', 'dictation') THEN 'dictation'
                ELSE 'text_input'
            END,
            configuration = CASE
                WHEN q.question_type IN (
                    'multiple_choice', 'choose_meaning', 'image_matching'
                )
                AND jsonb_array_length(COALESCE(q.options, '[]'::jsonb)) >= 2
                THEN jsonb_build_object(
                    'options',
                    (
                        SELECT jsonb_agg(
                            jsonb_build_object('id', option_text, 'text', option_text)
                        )
                        FROM jsonb_array_elements_text(q.options) option_text
                    ),
                    'correct_option_ids',
                    jsonb_build_array(q.correct_answer)
                )
                ELSE jsonb_build_object(
                    'accepted_answers',
                    jsonb_build_array(q.correct_answer),
                    'normalization',
                    jsonb_build_object(
                        'trim_whitespace', true,
                        'collapse_whitespace', true,
                        'unicode_form', 'NFKC',
                        'case_sensitive', false,
                        'punctuation', 'preserve',
                        'pinyin_tones', 'preserve'
                    )
                )
            END
        FROM exercises e
        JOIN exercise_sets es ON es.id = e.exercise_set_id
        WHERE
            e.external_id = 'legacy-question-' || q.id
            AND es.lesson_id = q.lesson_id
        """
    )
    op.add_column('user_grammar_progress', sa.Column('practiced_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_grammar_progress', sa.Column('correct_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_grammar_progress', sa.Column('incorrect_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_grammar_progress', sa.Column('first_practiced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_grammar_progress', sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_grammar_progress_last_practiced_at'), 'user_grammar_progress', ['last_practiced_at'], unique=False)
    op.create_check_constraint(
        'ck_user_grammar_progress_counts',
        'user_grammar_progress',
        'practiced_count >= 0 AND correct_count >= 0 AND incorrect_count >= 0',
    )
    op.add_column('user_vocabulary_progress', sa.Column('practiced_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_vocabulary_progress', sa.Column('correct_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_vocabulary_progress', sa.Column('incorrect_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_vocabulary_progress', sa.Column('first_practiced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_vocabulary_progress', sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_vocabulary_progress_last_practiced_at'), 'user_vocabulary_progress', ['last_practiced_at'], unique=False)
    op.create_check_constraint(
        'ck_user_vocabulary_progress_counts',
        'user_vocabulary_progress',
        'practiced_count >= 0 AND correct_count >= 0 AND incorrect_count >= 0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ck_user_vocabulary_progress_counts',
        'user_vocabulary_progress',
        type_='check',
    )
    op.drop_index(op.f('ix_user_vocabulary_progress_last_practiced_at'), table_name='user_vocabulary_progress')
    op.drop_column('user_vocabulary_progress', 'last_practiced_at')
    op.drop_column('user_vocabulary_progress', 'first_practiced_at')
    op.drop_column('user_vocabulary_progress', 'incorrect_count')
    op.drop_column('user_vocabulary_progress', 'correct_count')
    op.drop_column('user_vocabulary_progress', 'practiced_count')
    op.drop_constraint(
        'ck_user_grammar_progress_counts',
        'user_grammar_progress',
        type_='check',
    )
    op.drop_index(op.f('ix_user_grammar_progress_last_practiced_at'), table_name='user_grammar_progress')
    op.drop_column('user_grammar_progress', 'last_practiced_at')
    op.drop_column('user_grammar_progress', 'first_practiced_at')
    op.drop_column('user_grammar_progress', 'incorrect_count')
    op.drop_column('user_grammar_progress', 'correct_count')
    op.drop_column('user_grammar_progress', 'practiced_count')
    op.drop_constraint('ck_questions_sort_order', 'questions', type_='check')
    op.drop_constraint('ck_questions_prompt_not_empty', 'questions', type_='check')
    op.drop_constraint('ck_questions_points', 'questions', type_='check')
    op.drop_constraint('ck_questions_difficulty', 'questions', type_='check')
    op.drop_constraint('fk_questions_exercise_id_exercises', 'questions', type_='foreignkey')
    op.drop_constraint('uq_question_exercise_order', 'questions', type_='unique')
    op.drop_constraint('uq_question_exercise_external_id', 'questions', type_='unique')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_exercise_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_at')
    op.drop_column('questions', 'metadata')
    op.drop_column('questions', 'status')
    op.drop_column('questions', 'configuration')
    op.drop_column('questions', 'points')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'instruction')
    op.drop_column('questions', 'external_id')
    op.drop_column('questions', 'exercise_id')
    op.drop_index(op.f('ix_question_attempts_user_id'), table_name='question_attempts')
    op.drop_index('ix_question_attempts_user_attempted', table_name='question_attempts')
    op.drop_index('ix_question_attempts_session_question', table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_question_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_practice_session_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_is_correct'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_attempted_at'), table_name='question_attempts')
    op.drop_table('question_attempts')
    op.drop_index('ix_practice_sessions_user_status', table_name='practice_sessions')
    op.drop_index('ix_practice_sessions_user_lesson', table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_user_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_status'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_lesson_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_last_activity_at'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_exercise_set_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index(op.f('ix_exercises_vocabulary_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_status'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_skill'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_grammar_point_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_exercise_type'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_exercise_set_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_difficulty'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_exercise_sets_status'), table_name='exercise_sets')
    op.drop_index(op.f('ix_exercise_sets_skill'), table_name='exercise_sets')
    op.drop_index(op.f('ix_exercise_sets_lesson_id'), table_name='exercise_sets')
    op.drop_index(op.f('ix_exercise_sets_difficulty'), table_name='exercise_sets')
    op.drop_table('exercise_sets')
    bind = op.get_bind()
    postgresql.ENUM(name='practice_session_status').drop(bind, checkfirst=True)
    postgresql.ENUM(name='exercise_type').drop(bind, checkfirst=True)
    # PostgreSQL enum values cannot be removed safely in-place; the harmless
    # import_entity_type.exercises value remains after downgrade.
    # ### end Alembic commands ###
